name: data-stack

networks:
  db-network:
    driver: bridge

volumes:
  data-bd:

services:
  data-stack:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - data-bd:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5433:5432"
      - "6379:6379"
    networks:
      - db-network