version: '3.2'
name: data-stack

networks:
  db-network:
    driver: bridge

volumes:
  data-bd:

services:
  postgres:
    image: postgres:15.3-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - data-bd:/data/data

    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      db-network:
  redis:
    image: redis:6.0.9-alpine
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      db-network: