version: '3.8'

networks:
  db-network:
    external: true

services:
  node-app:
    build: .
    container_name: node-app
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - db-network